from __future__ import annotations
import sqlite3
from ..config_loader import root_path


class Database:
    def __init__(self, db_path: str):
        self.path = root_path(db_path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.init_schema()

    def connect(self):
        conn = sqlite3.connect(self.path, check_same_thread=False)
        conn.row_factory = sqlite3.Row
        return conn

    def init_schema(self):
        with self.connect() as con:
            con.executescript('''
            CREATE TABLE IF NOT EXISTS btc_radar_snapshots (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                price REAL,
                ls_posit_long REAL, ls_posit_short REAL,
                ls_ratio_long REAL, ls_ratio_short REAL,
                ls_account_long REAL, ls_account_short REAL,
                funding REAL, oi REAL, vwap REAL,
                cvd REAL, cvd_buy_vol REAL, cvd_sell_vol REAL,
                cvd_15m_ago REAL, cvd_delta_15m REAL, cvd_trend TEXT,
                price_updated_at TEXT, ls_updated_at TEXT, updated_at TEXT
            );

            CREATE TABLE IF NOT EXISTS btc_radar_market_monitor_snapshots (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                snapshot_hour TEXT NOT NULL,
                recorded_at TEXT NOT NULL,
                session TEXT,
                symbol TEXT NOT NULL,
                is_driver INTEGER DEFAULT 0,
                price REAL,
                price_change_1h_pct REAL,
                price_change_4h_pct REAL,
                price_change_24h_pct REAL,
                btc_price REAL,
                btc_change_1h_pct REAL,
                btc_change_4h_pct REAL,
                btc_change_24h_pct REAL,
                reaction_ratio_1h REAL,
                reaction_ratio_4h REAL,
                reaction_ratio_24h REAL,
                reaction_direction_1h TEXT,
                ls_posit_long REAL,
                ls_posit_short REAL,
                ls_ratio_long REAL,
                ls_ratio_short REAL,
                ls_account_long REAL,
                ls_account_short REAL,
                funding REAL,
                next_funding REAL,
                oi REAL,
                cvd REAL,
                cvd_delta_15m REAL,
                cvd_trend TEXT,
                crowding_side TEXT,
                agreement_with_btc TEXT,
                btc_link_strength TEXT,
                session_phase TEXT,
                hypothesis_tags TEXT,
                raw_json TEXT,
                UNIQUE(snapshot_hour, symbol)
            );

            CREATE TABLE IF NOT EXISTS btc_radar_market_daily_reports (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                day TEXT NOT NULL UNIQUE,
                generated_at TEXT NOT NULL,
                snapshot_hours INTEGER DEFAULT 0,
                sessions_json TEXT,
                btc_day_change_pct REAL,
                story TEXT,
                summary_json TEXT,
                timeline_json TEXT,
                hypothesis_json TEXT,
                raw_json TEXT
            );
            CREATE TABLE IF NOT EXISTS btc_radar_signals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                state TEXT, recommendation TEXT, score REAL, spread REAL,
                long_votes INTEGER, short_votes INTEGER, created_at TEXT
            );
            CREATE TABLE IF NOT EXISTS btc_radar_spread_history (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                state TEXT,
                recommendation TEXT,
                score REAL,
                spread REAL,
                btc_ls_posit_long REAL,
                btc_ls_ratio_long REAL,
                btc_ls_account_long REAL,
                ls_updated_at TEXT,
                created_at TEXT
            );

            CREATE TABLE IF NOT EXISTS btc_radar_coinalyze_history (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                coinalyze_symbol TEXT,
                ts INTEGER NOT NULL,
                interval TEXT DEFAULT '1hour',
                oi REAL,
                funding_rate REAL,
                predicted_funding_rate REAL,
                ls_ratio REAL,
                ls_long REAL,
                ls_short REAL,
                long_liquidations REAL,
                short_liquidations REAL,
                raw_json TEXT,
                created_at TEXT,
                UNIQUE(symbol, ts)
            );

            CREATE TABLE IF NOT EXISTS btc_radar_job_runs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                job_name TEXT NOT NULL,
                started_at TEXT,
                finished_at TEXT,
                status TEXT NOT NULL,
                rows_saved INTEGER DEFAULT 0,
                duration_ms INTEGER,
                error TEXT,
                details_json TEXT,
                created_at TEXT NOT NULL
            );
            CREATE INDEX IF NOT EXISTS idx_btc_radar_job_runs_name_id
                ON btc_radar_job_runs(job_name, id);

            CREATE TABLE IF NOT EXISTS btc_radar_manual_trades (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT, direction TEXT, size_usd REAL,
                entry_price REAL, current_price REAL,
                pnl_usd REAL DEFAULT 0, pnl_pct REAL DEFAULT 0,
                status TEXT DEFAULT 'OPEN', opened_at TEXT, closed_at TEXT,
                exit_price REAL,
                decision_judgment TEXT,
                decision_snapshot_json TEXT,
                btc_state_at_entry TEXT,
                btc_recommendation_at_entry TEXT,
                btc_score_at_entry REAL,
                btc_spread_at_entry REAL,
                btc_ls_posit_long_at_entry REAL,
                btc_ls_ratio_long_at_entry REAL,
                btc_ls_account_long_at_entry REAL,
                follow_score_at_entry REAL,
                btc_cvd_at_entry REAL,
                btc_cvd_15m_ago_at_entry REAL,
                btc_cvd_delta_15m_at_entry REAL,
                btc_cvd_trend_at_entry TEXT,
                follower_cvd_at_entry REAL,
                follower_cvd_15m_ago_at_entry REAL,
                follower_cvd_delta_15m_at_entry REAL,
                follower_cvd_trend_at_entry TEXT,
                followers_consensus_short_score_at_entry REAL,
                followers_consensus_short_state_at_entry TEXT,
                followers_consensus_long_score_at_entry REAL,
                followers_consensus_long_state_at_entry TEXT,
                followers_consensus_positive_funding_count_at_entry INTEGER,
                followers_consensus_negative_funding_count_at_entry INTEGER,
                followers_consensus_transition_count_at_entry INTEGER,
                followers_consensus_strong_agreement_count_at_entry INTEGER,
                followers_consensus_json TEXT,
                btc_cvd_at_close REAL,
                btc_cvd_delta_15m_at_close REAL,
                btc_cvd_trend_at_close TEXT,
                btc_cvd_delta_entry_to_close REAL,
                follower_cvd_at_close REAL,
                follower_cvd_delta_15m_at_close REAL,
                follower_cvd_trend_at_close TEXT,
                follower_cvd_delta_entry_to_close REAL
            );
            CREATE TABLE IF NOT EXISTS btc_radar_closed_trades (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                trade_id INTEGER,
                symbol TEXT, direction TEXT, size_usd REAL,
                entry_price REAL, exit_price REAL,
                pnl_usd REAL, pnl_pct REAL,
                opened_at TEXT, closed_at TEXT, duration_sec INTEGER,
                decision_judgment TEXT,
                decision_snapshot_json TEXT,
                btc_state_at_entry TEXT,
                btc_recommendation_at_entry TEXT,
                btc_score_at_entry REAL,
                btc_spread_at_entry REAL,
                btc_ls_posit_long_at_entry REAL,
                btc_ls_ratio_long_at_entry REAL,
                btc_ls_account_long_at_entry REAL,
                follow_score_at_entry REAL,
                btc_cvd_at_entry REAL,
                btc_cvd_15m_ago_at_entry REAL,
                btc_cvd_delta_15m_at_entry REAL,
                btc_cvd_trend_at_entry TEXT,
                follower_cvd_at_entry REAL,
                follower_cvd_15m_ago_at_entry REAL,
                follower_cvd_delta_15m_at_entry REAL,
                follower_cvd_trend_at_entry TEXT,
                followers_consensus_short_score_at_entry REAL,
                followers_consensus_short_state_at_entry TEXT,
                followers_consensus_long_score_at_entry REAL,
                followers_consensus_long_state_at_entry TEXT,
                followers_consensus_positive_funding_count_at_entry INTEGER,
                followers_consensus_negative_funding_count_at_entry INTEGER,
                followers_consensus_transition_count_at_entry INTEGER,
                followers_consensus_strong_agreement_count_at_entry INTEGER,
                followers_consensus_json TEXT,
                btc_cvd_at_close REAL,
                btc_cvd_delta_15m_at_close REAL,
                btc_cvd_trend_at_close TEXT,
                btc_cvd_delta_entry_to_close REAL,
                follower_cvd_at_close REAL,
                follower_cvd_delta_15m_at_close REAL,
                follower_cvd_trend_at_close TEXT,
                follower_cvd_delta_entry_to_close REAL
            );
            ''')
            self._migrate_columns(con)

    def _migrate_columns(self, con):
        """Safe additive migrations for existing btc_radar.db files."""
        migrations = {
            'btc_radar_snapshots': {
                'cvd_15m_ago': 'REAL',
                'cvd_delta_15m': 'REAL',
                'cvd_trend': 'TEXT',
            },
            'btc_radar_manual_trades': {
                'entry_snapshot_version': 'TEXT',
                'btc_long_votes_at_entry': 'INTEGER',
                'btc_short_votes_at_entry': 'INTEGER',
                'btc_dominant_votes_at_entry': 'INTEGER',
                'btc_long_score_at_entry': 'REAL',
                'btc_short_score_at_entry': 'REAL',
                'btc_narrative_at_entry': 'TEXT',
                'btc_price_at_entry': 'REAL',
                'btc_ls_posit_short_at_entry': 'REAL',
                'btc_ls_ratio_short_at_entry': 'REAL',
                'btc_ls_account_short_at_entry': 'REAL',
                'btc_funding_at_entry': 'REAL',
                'btc_oi_at_entry': 'REAL',
                'btc_vwap_at_entry': 'REAL',
                'btc_health_status_at_entry': 'TEXT',
                'btc_health_score_at_entry': 'REAL',
                'btc_preferred_direction_at_entry': 'TEXT',
                'follower_price_at_entry': 'REAL',
                'follower_ls_posit_long_at_entry': 'REAL',
                'follower_ls_posit_short_at_entry': 'REAL',
                'follower_ls_ratio_long_at_entry': 'REAL',
                'follower_ls_ratio_short_at_entry': 'REAL',
                'follower_ls_account_long_at_entry': 'REAL',
                'follower_ls_account_short_at_entry': 'REAL',
                'follower_funding_at_entry': 'REAL',
                'follower_oi_at_entry': 'REAL',
                'follower_vwap_at_entry': 'REAL',
                'follower_health_status_at_entry': 'TEXT',
                'follower_health_score_at_entry': 'REAL',
                'follower_preferred_direction_at_entry': 'TEXT',
                'follower_spread_at_entry': 'REAL',
                'follower_long_votes_at_entry': 'INTEGER',
                'follower_short_votes_at_entry': 'INTEGER',
                'follower_dominant_votes_at_entry': 'INTEGER',
                'follower_long_score_at_entry': 'REAL',
                'follower_short_score_at_entry': 'REAL',
                'follower_narrative_at_entry': 'TEXT',
                'followers_consensus_short_score_at_entry': 'REAL',
                'followers_consensus_short_state_at_entry': 'TEXT',
                'followers_consensus_long_score_at_entry': 'REAL',
                'followers_consensus_long_state_at_entry': 'TEXT',
                'followers_consensus_positive_funding_count_at_entry': 'INTEGER',
                'followers_consensus_negative_funding_count_at_entry': 'INTEGER',
                'followers_consensus_transition_count_at_entry': 'INTEGER',
                'followers_consensus_strong_agreement_count_at_entry': 'INTEGER',
                'followers_consensus_json': 'TEXT',
                'exit_reason': 'TEXT',
                'auto_guard_reason': 'TEXT',
                'decision_judgment': 'TEXT',
                'decision_snapshot_json': 'TEXT',
                'btc_state_at_entry': 'TEXT',
                'btc_recommendation_at_entry': 'TEXT',
                'btc_score_at_entry': 'REAL',
                'btc_spread_at_entry': 'REAL',
                'btc_ls_posit_long_at_entry': 'REAL',
                'btc_ls_ratio_long_at_entry': 'REAL',
                'btc_ls_account_long_at_entry': 'REAL',
                'follow_score_at_entry': 'REAL',
                'btc_cvd_at_entry': 'REAL',
                'btc_cvd_15m_ago_at_entry': 'REAL',
                'btc_cvd_delta_15m_at_entry': 'REAL',
                'btc_cvd_trend_at_entry': 'TEXT',
                'follower_cvd_at_entry': 'REAL',
                'follower_cvd_15m_ago_at_entry': 'REAL',
                'follower_cvd_delta_15m_at_entry': 'REAL',
                'follower_cvd_trend_at_entry': 'TEXT',
                'btc_cvd_at_close': 'REAL',
                'btc_cvd_delta_15m_at_close': 'REAL',
                'btc_cvd_trend_at_close': 'TEXT',
                'btc_cvd_delta_entry_to_close': 'REAL',
                'follower_cvd_at_close': 'REAL',
                'follower_cvd_delta_15m_at_close': 'REAL',
                'follower_cvd_trend_at_close': 'TEXT',
                'follower_cvd_delta_entry_to_close': 'REAL',
            },
            'btc_radar_closed_trades': {
                'entry_snapshot_version': 'TEXT',
                'btc_long_votes_at_entry': 'INTEGER',
                'btc_short_votes_at_entry': 'INTEGER',
                'btc_dominant_votes_at_entry': 'INTEGER',
                'btc_long_score_at_entry': 'REAL',
                'btc_short_score_at_entry': 'REAL',
                'btc_narrative_at_entry': 'TEXT',
                'btc_price_at_entry': 'REAL',
                'btc_ls_posit_short_at_entry': 'REAL',
                'btc_ls_ratio_short_at_entry': 'REAL',
                'btc_ls_account_short_at_entry': 'REAL',
                'btc_funding_at_entry': 'REAL',
                'btc_oi_at_entry': 'REAL',
                'btc_vwap_at_entry': 'REAL',
                'btc_health_status_at_entry': 'TEXT',
                'btc_health_score_at_entry': 'REAL',
                'btc_preferred_direction_at_entry': 'TEXT',
                'follower_price_at_entry': 'REAL',
                'follower_ls_posit_long_at_entry': 'REAL',
                'follower_ls_posit_short_at_entry': 'REAL',
                'follower_ls_ratio_long_at_entry': 'REAL',
                'follower_ls_ratio_short_at_entry': 'REAL',
                'follower_ls_account_long_at_entry': 'REAL',
                'follower_ls_account_short_at_entry': 'REAL',
                'follower_funding_at_entry': 'REAL',
                'follower_oi_at_entry': 'REAL',
                'follower_vwap_at_entry': 'REAL',
                'follower_health_status_at_entry': 'TEXT',
                'follower_health_score_at_entry': 'REAL',
                'follower_preferred_direction_at_entry': 'TEXT',
                'follower_spread_at_entry': 'REAL',
                'follower_long_votes_at_entry': 'INTEGER',
                'follower_short_votes_at_entry': 'INTEGER',
                'follower_dominant_votes_at_entry': 'INTEGER',
                'follower_long_score_at_entry': 'REAL',
                'follower_short_score_at_entry': 'REAL',
                'follower_narrative_at_entry': 'TEXT',
                'followers_consensus_short_score_at_entry': 'REAL',
                'followers_consensus_short_state_at_entry': 'TEXT',
                'followers_consensus_long_score_at_entry': 'REAL',
                'followers_consensus_long_state_at_entry': 'TEXT',
                'followers_consensus_positive_funding_count_at_entry': 'INTEGER',
                'followers_consensus_negative_funding_count_at_entry': 'INTEGER',
                'followers_consensus_transition_count_at_entry': 'INTEGER',
                'followers_consensus_strong_agreement_count_at_entry': 'INTEGER',
                'followers_consensus_json': 'TEXT',
                'exit_reason': 'TEXT',
                'auto_guard_reason': 'TEXT',
                'decision_judgment': 'TEXT',
                'decision_snapshot_json': 'TEXT',
                'btc_state_at_entry': 'TEXT',
                'btc_recommendation_at_entry': 'TEXT',
                'btc_score_at_entry': 'REAL',
                'btc_spread_at_entry': 'REAL',
                'btc_ls_posit_long_at_entry': 'REAL',
                'btc_ls_ratio_long_at_entry': 'REAL',
                'btc_ls_account_long_at_entry': 'REAL',
                'follow_score_at_entry': 'REAL',
                'btc_cvd_at_entry': 'REAL',
                'btc_cvd_15m_ago_at_entry': 'REAL',
                'btc_cvd_delta_15m_at_entry': 'REAL',
                'btc_cvd_trend_at_entry': 'TEXT',
                'follower_cvd_at_entry': 'REAL',
                'follower_cvd_15m_ago_at_entry': 'REAL',
                'follower_cvd_delta_15m_at_entry': 'REAL',
                'follower_cvd_trend_at_entry': 'TEXT',
                'btc_cvd_at_close': 'REAL',
                'btc_cvd_delta_15m_at_close': 'REAL',
                'btc_cvd_trend_at_close': 'TEXT',
                'btc_cvd_delta_entry_to_close': 'REAL',
                'follower_cvd_at_close': 'REAL',
                'follower_cvd_delta_15m_at_close': 'REAL',
                'follower_cvd_trend_at_close': 'TEXT',
                'follower_cvd_delta_entry_to_close': 'REAL',
            },
        }
        for table, cols in migrations.items():
            existing = {r['name'] for r in con.execute(f'PRAGMA table_info({table})').fetchall()}
            for name, col_type in cols.items():
                if name not in existing:
                    con.execute(f'ALTER TABLE {table} ADD COLUMN {name} {col_type}')
